### ISSUE TITLE
OkHttp throws error at launch

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-android#42]
<details>
<summary>logs</summary>

```log
W/ieringe.workout( 2152): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (max-target-q,core-platform-api, reflection, denied)
W/OkHttp  ( 2152): unable to load android socket classes
W/OkHttp  ( 2152): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  ( 2152): 	at java.lang.Class.getMethod(Class.java:2103)
W/OkHttp  ( 2152): 	at java.lang.Class.getDeclaredMethod(Class.java:2081)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  ( 2152): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  ( 2152): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  ( 2152): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
W/OkHttp  ( 2152): 	at com.chargebee.android.resources.BaseResource.<init>(BaseResource.kt:17)
W/OkHttp  ( 2152): 	at com.chargebee.android.resources.LoggerResource.<init>(LoggerResource.kt:10)
W/OkHttp  ( 2152): 	at com.chargebee.android.loggers.CBLogger.postLog(CBLogger.kt:28)
W/OkHttp  ( 2152): 	at com.chargebee.android.loggers.CBLogger.postLog$default(CBLogger.kt:18)
W/OkHttp  ( 2152): 	at com.chargebee.android.loggers.CBLogger.info(CBLogger.kt:15)
W/OkHttp  ( 2152): 	at com.chargebee.android.models.ResultHandler$Companion$safeExecuter$1.invokeSuspend(ResultHandler.kt:43)
W/OkHttp  ( 2152): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/OkHttp  ( 2152): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/OkHttp  ( 2152): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/OkHttp  ( 2152): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/OkHttp  ( 2152): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/OkHttp  ( 2152): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
</details>

We're using an older version of chargebee-android and we had to downgrade the billingclient version for it to work in our usecase. Take this issue with a grain of salt.

**Comment by ciriousjoker** [comment]
Haven't had this issue in a long time now, closing this.
