### ISSUE TITLE
App crashes when receiving the PURCHASES_UPDATED intent

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-android#90]
> Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.billing.PURCHASES_UPDATED flg=0x10 pkg=com.dieringe.workout (has extras) } in u2.f1@c9ed868
>        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1929)
>        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
>        at android.os.Handler.handleCallback(Handler.java:942)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8762)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

> Caused by uj.s: lateinit property product has not been initialized
>        at com.chargebee.android.billingservice.BillingClientManager.acknowledgePurchase(:6)
>        at com.chargebee.android.billingservice.BillingClientManager.onPurchasesUpdated(:139)
>        at u2.f1.onReceive(SourceFile:1)
>        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1919)
>        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
>        at android.os.Handler.handleCallback(Handler.java:942)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8762)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Both of these together caused an app crash in production.
Maybe another ProGuard issue due to missing rules?

**Comment by ciriousjoker** [comment]
This keeps occurring in production even after updating the ProGuard rules. No idea how to reproduce it in development.

**Comment by cb-haripriyan** [comment]
Hi @ciriousjoker -
Thanks for bringing reporting. We are looking into this and will update here about the progress.

**Comment by ciriousjoker** [comment]
@cb-haripriyan Any news?

**Comment by ciriousjoker** [comment]
@cb-haripriyan Is v1.2.1 also supposed to fix this?

**Comment by ciriousjoker** [comment]
@cb-haripriyan Any updates?
