### ISSUE TITLE
App crashes: "Reply already submitted"

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-android#91]
This currently affects a high percentage of our users.

> Fatal Exception: java.lang.IllegalStateException: Reply already submitted
>        at bh.c$g.a(SourceFile:1)
>        at lh.k$a$a.b(SourceFile:1)
>        at b4.b.f(SourceFile:1)
>        at b4.b.h(SourceFile:1)
>        at b4.b.b(SourceFile:1)
>        at b4.b$i.onError(SourceFile:1)
>        at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(SourceFile:2)
>        at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(SourceFile:1)
>        at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(SourceFile:2)
>        at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(SourceFile:1)
>        at com.chargebee.android.billingservice.BillingClientManager$createBillingClientStateListener$1.onBillingServiceDisconnected(:15)
>        at u2.v.onServiceDisconnected(SourceFile:1)
>        at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2368)
>        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2383)
>        at android.os.Handler.handleCallback(Handler.java:942)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8757)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by ciriousjoker** [comment]
- Related: https://github.com/chargebee/chargebee-flutter/issues/71

**Comment by ciriousjoker** [comment]
Here's also a better crashlog in debug mode.
I managed to reproduce it by logging into Google Play on an emulator after opening the app:

1. Open the app
2. Open Play Store
3. Sign in
4. Reopen app
5. App crashes

However, this clearly affects production users as well, who are probably already logged into Google Play since they couldn't download the app otherwise.

> I/FA      ( 9108): Application backgrounded at: timestamp_millis: 1698896011747
> W/BillingClient( 9108): Billing service disconnected.
> W/BillingClient( 9108): Billing service disconnected.
> I/        ( 9108): onBillingServiceDisconnected
> D/AndroidRuntime( 9108): Shutting down VM
> E/AndroidRuntime( 9108): FATAL EXCEPTION: main
> E/AndroidRuntime( 9108): Process: ..., PID: 9108
> E/AndroidRuntime( 9108): java.lang.IllegalStateException: Reply already submitted
> E/AndroidRuntime( 9108): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
> E/AndroidRuntime( 9108): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:268)
> E/AndroidRuntime( 9108): 	at com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin.error(ChargebeeFlutterSdkPlugin.kt:530)
> E/AndroidRuntime( 9108): 	at com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin.onError(ChargebeeFlutterSdkPlugin.kt:511)
> E/AndroidRuntime( 9108): 	at com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin.access$onError(ChargebeeFlutterSdkPlugin.kt:26)
> E/AndroidRuntime( 9108): 	at com.chargebee.flutter.sdk.ChargebeeFlutterSdkPlugin$retrieveProducts$1.onError(ChargebeeFlutterSdkPlugin.kt:159)
> E/AndroidRuntime( 9108): 	at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(BillingClientManager.kt:51)
> E/AndroidRuntime( 9108): 	at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$2.invoke(BillingClientManager.kt:21)
> E/AndroidRuntime( 9108): 	at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(BillingClientManager.kt:69)
> E/AndroidRuntime( 9108): 	at com.chargebee.android.billingservice.BillingClientManager$retrieveProducts$3.invoke(BillingClientManager.kt:21)
> E/AndroidRuntime( 9108): 	at com.chargebee.android.billingservice.BillingClientManager$createBillingClientStateListener$1.onBillingServiceDisconnected(BillingClientManager.kt:511)
> E/AndroidRuntime( 9108): 	at com.android.billingclient.api.zzaf.onServiceDisconnected(com.android.billingclient:billing@@6.0.1:5)
> E/AndroidRuntime( 9108): 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2218)
> E/AndroidRuntime( 9108): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2233)
> E/AndroidRuntime( 9108): 	at android.os.Handler.handleCallback(Handler.java:958)
> E/AndroidRuntime( 9108): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime( 9108): 	at android.os.Looper.loopOnce(Looper.java:205)
> E/AndroidRuntime( 9108): 	at android.os.Looper.loop(Looper.java:294)
> E/AndroidRuntime( 9108): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
> E/AndroidRuntime( 9108): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 9108): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> E/AndroidRuntime( 9108): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by cb-haripriyan** [comment]
Hi @ciriousjoker -
Thanks for bringing reporting. We are looking into this and will update here about the progress.

**Comment by cb-haripriyan** [comment]
This [PR](https://github.com/chargebee/chargebee-android/pull/96) should fix this. This is fixed in version https://github.com/chargebee/chargebee-android/releases/tag/1.2.1

**Comment by ciriousjoker** [comment]
This isn't fixed in **[v2.0.0-beta-1](https://github.com/chargebee/chargebee-android/releases/tag/2.0.0-beta-1)**

**Comment by cb-haripriyan** [comment]
@ciriousjoker Thanks for pointing out. We will fix this.

**Comment by cb-haripriyan** [comment]
@ciriousjoker Can you verify this with the latest beta?

**Comment by ciriousjoker** [comment]
Thanks a lot! We'll roll it out to production asap and I'll report back whether it's fixed or not

**Comment by samarthagarwalqb** [comment]
Any updates on this? Looks like the issue is also happening with the Flutter SDK since it uses the same Android SDK under the hood. This is filling up our Crashlytics dashboard pretty quickly.

**Comment by cb-haripriyan** [comment]
@samarthagarwalqb For the the chargebee-flutter sdk, [v1.0.0-beta.4](https://github.com/chargebee/chargebee-flutter/releases/tag/v1.0.0-beta.4) fixes this.

**Comment by ciriousjoker** [comment]
@cb-haripriyan We've monitored the update for a while now and no more crashes are reported, thanks a lot for the quick fix!
